name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code
    - name: Test1
      id: t1
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "yyyy-MM-dd"

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: yaming116/fun-asr
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
        tags: ${{ steps.t1.outputs.year }}-${{ steps.t1.outputs.month }}-${{ steps.t1.outputs.day }}, latest
        registry: docker.io
        dockerfile: Dockerfile
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#    - name: login aliyun
#      run: echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login -u ${{secrets.ALIYUN_USERNAME}} registry.cn-hangzhou.aliyuncs.com --password-stdin
#    - name: push to aliyun
#      run: |-
#        docker pull ${{ secrets.DOCKER_USERNAME }}/stt:latest
#        docker tag ${{ secrets.DOCKER_USERNAME }}/stt:latest registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_USERNAME }}/stt:latest
#        docker tag ${{ secrets.DOCKER_USERNAME }}/stt:latest registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_USERNAME }}/stt:${{ steps.t1.outputs.year }}-${{ steps.t1.outputs.month }}-${{ steps.t1.outputs.day }}
#        docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_USERNAME }}/stt:latest
#        docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_USERNAME }}/stt:${{ steps.t1.outputs.year }}-${{ steps.t1.outputs.month }}-${{ steps.t1.outputs.day }}



  
